import { test, expect, type Page } from '@playwright/test'
import { demoBoard } from '../fixtures/demoBoard'

const number = async (page: Page, name: string, value: number) => {
  const field = page.getByLabel(`Artwork ${name}`, { exact: true })
  await field.fill(String(value)); await field.press('Tab')
  await expect(field).toHaveValue(String(value))
}
const open = async (page: Page) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(demoBoard)
}
const graphic = async (page: Page, name = 'A.svg', x = 20, y = 40, width = 10) => {
  await page.getByLabel('Choose SVG graphic').setInputFiles({ name, mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" fill="#fc7f9e"/></svg>') })
  await expect(page.getByLabel('Layer name', { exact: true })).toHaveValue(name)
  await number(page, 'width', width)
  await number(page, 'x', x)
  await number(page, 'y', y)
}
const action = (page: Page, name: string) => page.getByRole('button', { name, exact: true }).click()

test('aligns to PCB bounds, undoes and saves alignment', async ({ page }) => {
  await open(page)
  await graphic(page)
  await expect(page.getByLabel('Align to', { exact: true })).toHaveValue('board')
  await action(page, 'Align left')
  await expect(page.getByLabel('Artwork x', { exact: true })).toHaveValue('10')
  await action(page, 'Align horizontal center')
  await expect(page.getByLabel('Artwork x', { exact: true })).toHaveValue('33')
  await action(page, 'Align right')
  await expect(page.getByLabel('Artwork x', { exact: true })).toHaveValue('56')
  await action(page, 'Align top')
  await expect(page.getByLabel('Artwork y', { exact: true })).toHaveValue('20')
  await action(page, 'Align vertical center')
  await expect(page.getByLabel('Artwork y', { exact: true })).toHaveValue('65')
  await action(page, 'Align bottom')
  await expect(page.getByLabel('Artwork y', { exact: true })).toHaveValue('110')
  await action(page, 'Undo')
  await expect(page.getByLabel('Artwork y', { exact: true })).toHaveValue('65')
  await action(page, 'Redo')
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await action(page, 'A.svg')
  await expect(page.getByLabel('Artwork x', { exact: true })).toHaveValue('56')
  await expect(page.getByLabel('Artwork y', { exact: true })).toHaveValue('110')
})

const select = async (page: Page, names: string[]) => {
  await action(page, names[0]!)
  for (const name of names.slice(1)) await page.getByRole('button', { name, exact: true }).click({ modifiers: ['Shift'] })
}
const positions = async (page: Page) => page.locator('[data-artwork-layer] image').evaluateAll(images => images.map(image => ({ x: Number(image.getAttribute('x')), y: Number(image.getAttribute('y')) })))

test('aligns a multi-selection to selection bounds or a fixed key graphic', async ({ page }) => {
  await open(page)
  await graphic(page, 'A.svg', 15, 30, 10)
  await graphic(page, 'B.svg', 40, 70, 20)
  await select(page, ['A.svg', 'B.svg'])
  await expect(page.getByLabel('Align to', { exact: true })).toHaveValue('selection')
  await expect(page.getByRole('button', { name: 'A.svg', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'B.svg', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await action(page, 'Align left')
  await expect.poll(() => positions(page)).toEqual([{ x: 15, y: 30 }, { x: 15, y: 70 }])
  await action(page, 'Undo')
  await expect.poll(() => positions(page)).toEqual([{ x: 15, y: 30 }, { x: 40, y: 70 }])
  await page.getByLabel('Align to', { exact: true }).selectOption('key')
  await page.getByLabel('Key object', { exact: true }).selectOption({ label: 'B.svg' })
  await action(page, 'Align vertical center')
  await expect.poll(() => positions(page)).toEqual([{ x: 15, y: 75 }, { x: 40, y: 70 }])
  await page.getByLabel('Align to', { exact: true }).selectOption('board')
  await action(page, 'Align right')
  await expect.poll(() => positions(page)).toEqual([{ x: 56, y: 75 }, { x: 46, y: 70 }])
  await page.screenshot({ path: 'test-results/artwork-alignment-desktop.png' })
})

test('distributes different sizes with equal gaps and one undo step', async ({ page }) => {
  await open(page)
  await graphic(page, 'A.svg', 12, 25, 6)
  await graphic(page, 'B.svg', 25, 40, 10)
  await graphic(page, 'C.svg', 48, 100, 12)
  await select(page, ['A.svg', 'B.svg', 'C.svg'])
  await action(page, 'Distribute horizontal spacing')
  // Span 12..60, widths 6+10+12 -> two 10 mm gaps.
  await expect.poll(() => positions(page)).toEqual([{ x: 12, y: 25 }, { x: 28, y: 40 }, { x: 48, y: 100 }])
  await action(page, 'Undo')
  await expect.poll(() => positions(page)).toEqual([{ x: 12, y: 25 }, { x: 25, y: 40 }, { x: 48, y: 100 }])
  await action(page, 'Distribute vertical spacing')
  // Span 25..112, widths along Y total 28 -> two 29.5 mm gaps.
  await expect.poll(() => positions(page)).toEqual([{ x: 12, y: 25 }, { x: 25, y: 60.5 }, { x: 48, y: 100 }])
  await page.getByLabel('Align to', { exact: true }).selectOption('board')
  await action(page, 'Distribute horizontal spacing')
  await expect.poll(() => positions(page)).toEqual([{ x: 10, y: 25 }, { x: 30, y: 60.5 }, { x: 54, y: 100 }])
  await page.getByLabel('Align to', { exact: true }).selectOption('key')
  await expect(page.getByRole('button', { name: 'Distribute horizontal spacing', exact: true })).toBeDisabled()
  await select(page, ['A.svg', 'B.svg'])
  await expect(page.getByRole('button', { name: 'Distribute horizontal spacing', exact: true })).toBeDisabled()
})

for (const side of ['Front', 'Back']) test(`aligns rotated ${side.toLowerCase()} artwork using its displayed bounds`, async ({ page }) => {
  await open(page)
  await action(page, side)
  await graphic(page, 'Rotated.svg', 30, 50, 10)
  await number(page, 'rotation', 45)
  await action(page, 'Align left')
  // A 10 mm square at 45 degrees has a 14.142 mm bounding box.
  expect(Number(await page.getByLabel('Artwork x', { exact: true }).inputValue())).toBeCloseTo(side === 'Front' ? 12.071 : 53.929, 2)
  await action(page, 'Align top')
  expect(Number(await page.getByLabel('Artwork y', { exact: true }).inputValue())).toBeCloseTo(22.071, 2)
  await action(page, 'Align right')
  expect(Number(await page.getByLabel('Artwork x', { exact: true }).inputValue())).toBeCloseTo(side === 'Front' ? 53.929 : 12.071, 2)
  await expect(page.getByLabel('Artwork rotation', { exact: true })).toHaveValue('45')
  await expect(page.getByLabel('Artwork width', { exact: true })).toHaveValue('10')
  await action(page, side === 'Front' ? 'Back' : 'Front')
  await expect(page.getByRole('region', { name: 'Artwork alignment' })).toHaveCount(0)
  await action(page, side)
  await expect(page.locator('[data-resize-handle]')).toHaveCount(0)
})

test('Shift-click selects on canvas, drags together and deletes in one undo step', async ({ page }) => {
  await open(page)
  await graphic(page, 'A.svg', 15, 30, 10)
  await graphic(page, 'B.svg', 40, 70, 10)
  const hits = page.locator('[data-artwork-layer] > rect')
  await hits.first().click()
  await hits.last().click({ modifiers: ['Shift'] })
  await expect(page.locator('[data-resize-handle]')).toHaveCount(0)
  await expect(page.getByLabel('Align to', { exact: true })).toHaveValue('selection')
  const box = (await hits.first().boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 20, box.y + box.height / 2 + 15, { steps: 4 }); await page.mouse.up()
  const moved = await positions(page)
  expect(moved[0]!.x).toBeGreaterThan(15)
  expect(moved[1]!.x - moved[0]!.x).toBeCloseTo(25, 6)
  expect(moved[1]!.y - moved[0]!.y).toBeCloseTo(40, 6)
  await action(page, 'Undo')
  await expect.poll(() => positions(page)).toEqual([{ x: 15, y: 30 }, { x: 40, y: 70 }])
  // Shift-click toggles membership without moving the remaining graphic.
  await hits.first().click({ modifiers: ['Shift'] })
  await expect(page.getByRole('button', { name: 'A.svg', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await hits.first().click({ modifiers: ['Shift'] })
  await page.keyboard.press('Delete')
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(0)
  await action(page, 'Undo')
  await expect.poll(() => positions(page)).toEqual([{ x: 15, y: 30 }, { x: 40, y: 70 }])
})

test('hidden graphics, folders, and KiCad references remain outside alignment', async ({ page }) => {
  await open(page)
  await graphic(page, 'A.svg', 15, 30, 10)
  await graphic(page, 'B.svg', 40, 70, 10)
  await select(page, ['A.svg', 'B.svg'])
  await action(page, 'Toggle B.svg')
  await action(page, 'Align left')
  await action(page, 'Toggle B.svg')
  await expect.poll(() => positions(page)).toEqual([{ x: 10, y: 30 }, { x: 40, y: 70 }])
  await action(page, 'Add folder')
  await expect(page.getByRole('region', { name: 'Artwork alignment' })).toHaveCount(0)
  await graphic(page, 'Nested.svg', 30, 60, 5)
  await action(page, 'Toggle Folder 1')
  await expect(page.getByRole('region', { name: 'Artwork alignment' })).toHaveCount(0)
  await select(page, ['A.svg', 'B.svg'])
  await page.getByLabel('Align to', { exact: true }).selectOption('board')
  await action(page, 'Align right')
  await action(page, 'Toggle Folder 1')
  await expect.poll(() => positions(page)).toEqual([{ x: 56, y: 30 }, { x: 56, y: 70 }, { x: 30, y: 60 }])
  await action(page, 'KiCad silkscreen')
  await expect(page.getByRole('region', { name: 'Artwork alignment' })).toHaveCount(0)
})

test('alignment controls fit mobile and remain keyboard accessible', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await open(page)
  await graphic(page)
  const align = page.getByRole('region', { name: 'Artwork alignment' })
  await align.scrollIntoViewIfNeeded()
  const box = (await align.boundingBox())!
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: 'Align horizontal center', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Artwork x', { exact: true })).toHaveValue('33')
  await page.screenshot({ path: 'test-results/artwork-alignment-mobile.png' })
})

test('overlapping distribution persists in downloads without changing hidden or rear artwork', async ({ page }) => {
  await open(page)
  await graphic(page, 'Hidden.svg', 15, 80, 5)
  await action(page, 'Toggle Hidden.svg')
  await action(page, 'Back')
  await graphic(page, 'Rear.svg', 40, 60, 5)
  await action(page, 'Front')
  await graphic(page, 'A.svg', 10, 30, 20)
  await graphic(page, 'B.svg', 22, 30, 20)
  await graphic(page, 'C.svg', 30, 30, 20)
  await select(page, ['A.svg', 'B.svg', 'C.svg'])
  await action(page, 'Distribute horizontal spacing')
  await expect.poll(() => positions(page)).toEqual([{ x: 10, y: 30 }, { x: 20, y: 30 }, { x: 30, y: 30 }])
  const downloadPromise = page.waitForEvent('download')
  await action(page, 'Save project')
  const file = await downloadPromise
  const { readFile } = await import('node:fs/promises')
  const project = JSON.parse(await readFile((await file.path())!, 'utf8'))
  expect(project.artwork.map((item: { name: string; x: number; y: number; side: string; visible: boolean }) => ({ name: item.name, x: item.x, y: item.y, side: item.side, visible: item.visible }))).toEqual([
    { name: 'Hidden.svg', x: 15, y: 80, side: 'front', visible: false },
    { name: 'Rear.svg', x: 40, y: 60, side: 'back', visible: true },
    { name: 'A.svg', x: 10, y: 30, side: 'front', visible: true },
    { name: 'B.svg', x: 20, y: 30, side: 'front', visible: true },
    { name: 'C.svg', x: 30, y: 30, side: 'front', visible: true },
  ])
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.getByRole('region', { name: 'Artwork alignment' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/artwork-alignment-dark.png' })
})
