import { test, expect } from '@playwright/test'
import { demoBoard as fixture } from '../fixtures/demoBoard'
const graphic = { name: 'red-square.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" fill="red"/></svg>') }
test('imports an SVG export with its original class-based colors', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByLabel('Choose SVG graphic').setInputFiles('tests/fixtures/class-paints.svg')
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
  const source = decodeURIComponent((await page.locator('[data-artwork-layer] image').getAttribute('href'))!)
  expect(source).toContain('fill="#f4ebe2"')
  expect(source).toContain('fill="#fc7f9e"')
  expect(source).not.toContain('<style')
  expect(source).not.toContain('<metadata')
  await page.screenshot({ path: 'test-results/class-paints-import.png' })
  await page.getByLabel('Choose SVG graphic').setInputFiles({ name: 'linked.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><style>.paint { fill: url(https://example.com/paint.svg); }</style><rect class="paint" width="10" height="10"/></svg>') })
  await expect(page.getByRole('alert')).toContainText('external links')
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
})
test('imports SVG metadata without retaining it in artwork or saved projects', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByLabel('Choose SVG graphic').setInputFiles({
    name: 'export.svg', mimeType: 'image/svg+xml',
    buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 100 100"><metadata><rdf:RDF><rdf:Description><dc:creator>Editor export</dc:creator></rdf:Description></rdf:RDF></metadata><rect width="100" height="100" fill="red"/></svg>'),
  })
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
  const source = decodeURIComponent((await page.locator('[data-artwork-layer] image').getAttribute('href'))!)
  expect(source).not.toContain('<metadata')
  expect(source).not.toContain('<rdf:RDF')
  expect(source).toContain('<rect')
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
})
for (const key of ['Backspace', 'Delete']) {
  test(`${key} removes the selected image and undo restores it`, async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
    await page.getByLabel('Choose board export').setInputFiles(fixture)
    await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
    await page.getByRole('button', { name: 'red-square.svg', exact: true }).click()
    await page.keyboard.press(key)
    await expect(page.locator('[data-artwork-layer] image')).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
    // Text editing must not delete the selected graphic.
    await page.getByRole('button', { name: 'red-square.svg', exact: true }).click()
    await page.getByLabel('Layer name', { exact: true }).focus()
    await page.keyboard.press(key)
    await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
    await page.getByRole('button', { name: 'Delete red-square.svg', exact: true }).click()
    await expect(page.locator('[data-artwork-layer] image')).toHaveCount(0)
  })
}
test('nested folders and layers preserve artwork, visibility and hierarchy', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByRole('button', { name: 'Add folder', exact: true }).click()
  await page.getByLabel('Layer name', { exact: true }).fill('Dragon')
  await page.getByLabel('Layer name', { exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Add layer', exact: true }).click()
  await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
  await page.getByRole('button', { name: 'Collapse Dragon', exact: true }).click()
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toHaveCount(0)
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
  await page.getByRole('button', { name: 'Toggle Dragon', exact: true }).click()
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Expand Dragon', exact: true }).click()
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Layer 1', exact: true }).click()
  await expect(page.getByLabel('Move to')).not.toHaveValue('')
  // Descendants cannot become their own ancestors.
  await page.getByRole('button', { name: 'Dragon', exact: true }).click()
  await expect(page.getByLabel('Move to').locator('option')).toHaveCount(1)
  await page.getByRole('button', { name: 'Delete Dragon', exact: true }).click()
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'red-square.svg', exact: true }).click()
  await page.getByLabel('Move to').selectOption('')
  await page.getByRole('button', { name: 'Delete Dragon', exact: true }).click()
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/layers.png' })
})
test('imports, transforms, hides, reorders and undoes side-specific artwork', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toBeVisible()
  const width = page.getByLabel('Artwork width', { exact: true })
  await width.fill('12'); await width.press('Tab')
  await expect(page.getByLabel('Artwork height', { exact: true })).toHaveValue('12')
  await page.getByLabel('Artwork rotation').fill('35'); await page.getByLabel('Artwork rotation').press('Tab')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByLabel('Artwork rotation')).toHaveValue('0')
  const hit = page.locator('[data-artwork-layer] > rect').first()
  const before = await page.getByLabel('Artwork x', { exact: true }).inputValue()
  const box = (await hit.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 40, box.y + box.height / 2 + 10); await page.mouse.up()
  await expect(page.getByLabel('Artwork x', { exact: true })).not.toHaveValue(before)
  await page.getByRole('button', { name: 'Toggle red-square.svg' }).click()
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('[data-artwork-layer] image')).toHaveCount(1)
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Front', exact: true }).click()
  await page.getByLabel('Choose SVG graphic').setInputFiles({ name: 'unsafe.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>') })
  await expect(page.getByRole('alert')).toContainText('Unsupported SVG element')
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/artwork.png' })
})

test('project autosaves, downloads, and reopens with artwork intact', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
  const handle = page.getByLabel('Resize artwork', { exact: true })
  const h = (await handle.boundingBox())!
  await page.mouse.move(h.x + h.width / 2, h.y + h.height / 2)
  await page.mouse.down(); await page.mouse.move(h.x + 25, h.y + 25); await page.mouse.up()
  const width = await page.getByLabel('Artwork width', { exact: true }).inputValue()
  expect(Number(width)).toBeGreaterThan(28)
  const rotate = (await page.getByLabel('Rotate artwork', { exact: true }).boundingBox())!
  await page.mouse.move(rotate.x + rotate.width / 2, rotate.y + rotate.height / 2)
  await page.mouse.down(); await page.mouse.move(rotate.x + 35, rotate.y + 20); await page.mouse.up()
  await expect(page.getByLabel('Artwork rotation')).not.toHaveValue('0')
  await page.getByLabel('Artwork rotation').fill('25'); await page.getByLabel('Artwork rotation').press('Tab')
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect.poll(() => page.evaluate(() => new Promise(resolve => {
    const request = indexedDB.open('overprint', 1)
    request.onsuccess = () => { const db = request.result; const read = db.transaction('projects').objectStore('projects').get('current'); read.onsuccess = () => { resolve(JSON.parse(read.result ?? '{}').side); db.close() } }
  }))).toBe('back')
  await page.reload()
  await expect(page.getByRole('img', { name: 'Demo board back board preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Front', exact: true }).click()
  await page.getByRole('button', { name: 'red-square.svg', exact: true }).click()
  await expect(page.getByLabel('Artwork width', { exact: true })).toHaveValue(width)
  await expect(page.getByLabel('Artwork rotation')).toHaveValue('25')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save project', exact: true }).click()
  const file = await download
  const path = await file.path()
  await page.getByRole('button', { name: 'Delete red-square.svg' }).click()
  await page.getByLabel('Choose project file').setInputFiles(path!)
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toBeVisible()
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('All changes saved')
})

test('quota errors and corrupt project files preserve the current artwork', async ({ page }) => {
  await page.addInitScript(() => {
    IDBObjectStore.prototype.put = function() { throw new DOMException('Full', 'QuotaExceededError') }
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('Could not save locally')
  await page.getByLabel('Choose project file').setInputFiles({ name: 'broken.overprint', mimeType: 'application/json', buffer: Buffer.from('{"version":999}') })
  await expect(page.getByRole('status')).toContainText('Unsupported project version')
  await expect(page.getByRole('button', { name: 'red-square.svg', exact: true })).toBeVisible()
})

test('corrupt saved data stays untouched until explicit replacement', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('overprint-project-v1', 'broken'))
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('could not be restored')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await expect(page.getByRole('img', { name: 'Demo board front board preview' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('overprint-project-v1'))).toBe('broken')
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('All changes saved')
})

test('autosaves a board larger than the localStorage quota', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await expect(page.getByRole('img', { name: 'Demo board front board preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Save project', exact: true }).click()
  // A valid large SVG path represents a dense native board export.
  const { unzipSync, strFromU8 } = await import('fflate')
  const files = unzipSync(fixture.buffer)
  const manifest = JSON.parse(strFromU8(files['manifest.json']!))
  const project = { version: 1, board: { name: 'Large board', bounds: manifest.board.boundsMm, outline: 'M0 0 L70 0 L70 35 L0 35 Z', holes: '', layers: { 'front-silkscreen': ['M0 0 L1 1 Z '.repeat(550000)] } }, artwork: [], side: 'front', silk: false, mask: '#202723', fabrication: false }
  await page.getByLabel('Choose project file').setInputFiles({ name: 'large.overprint', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(project)) })
  await expect(page.getByRole('img', { name: 'Large board front board preview' })).toBeVisible()
  await page.keyboard.press('Control+s')
  await expect(page.getByRole('status')).toContainText('All changes saved')
  await page.reload()
  await expect(page.getByRole('img', { name: 'Large board front board preview' })).toBeVisible()
})

test('artwork uses fixed-size bounding-box handles and corner rotation zones', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
  const handles = page.locator('[data-resize-handle]')
  await expect(handles).toHaveCount(8)
  await expect(page.locator('[data-rotation-zone]')).toHaveCount(4)
  const square = handles.first().locator('[data-handle-square]')
  await expect.poll(async () => (await square.boundingBox())!.width).toBeCloseTo(8, 0)
  const canvas = page.getByRole('img', { name: 'Demo board front board preview' })
  const box = (await canvas.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.wheel(0, -300)
  await expect.poll(async () => (await square.boundingBox())!.width).toBeCloseTo(8, 0)
  await page.getByLabel('Rotate artwork', { exact: true }).hover()
  await expect(page.getByLabel('Rotate artwork', { exact: true })).toHaveCSS('cursor', /url\(/)
  await page.screenshot({ path: 'test-results/artwork-transform-handles.png' })
})

for (const side of ['Front', 'Back']) test(`resizing rotated ${side.toLowerCase()} artwork keeps its opposite handle anchored`, async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Import PCB', exact: true }).click()
  await page.getByLabel('Choose board export').setInputFiles(fixture)
  await page.getByRole('button', { name: side, exact: true }).click()
  await page.getByLabel('Choose SVG graphic').setInputFiles(graphic)
  const width = page.getByLabel('Artwork width', { exact: true })
  const rotation = page.getByLabel('Artwork rotation', { exact: true })
  await rotation.fill('30'); await rotation.press('Tab')
  const oldWidth = Number(await width.inputValue())
  const anchor = page.getByLabel('Resize artwork: top left', { exact: true })
  const a = (await anchor.boundingBox())!
  const handle = page.getByLabel('Resize artwork', { exact: true })
  const b = (await handle.boundingBox())!
  const ax = a.x + a.width / 2, ay = a.y + a.height / 2
  const bx = b.x + b.width / 2, by = b.y + b.height / 2
  await page.mouse.move(bx, by)
  await page.mouse.down()
  await page.mouse.move(bx + (bx - ax) * 0.2, by + (by - ay) * 0.2, { steps: 4 })
  await page.mouse.up()
  expect(Number(await width.inputValue())).toBeCloseTo(oldWidth * 1.2, 1)
  const after = (await anchor.boundingBox())!
  expect(after.x + after.width / 2).toBeCloseTo(ax, 0)
  expect(after.y + after.height / 2).toBeCloseTo(ay, 0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  expect(Number(await width.inputValue())).toBeCloseTo(oldWidth, 2)
  await expect(rotation).toHaveValue('30')
  const image = page.locator('[data-artwork-layer] image').first()
  const imageBefore = (await image.boundingBox())!
  const centered = (await handle.boundingBox())!
  await page.keyboard.down('Alt')
  await page.mouse.move(centered.x + centered.width / 2, centered.y + centered.height / 2)
  await page.mouse.down()
  await page.mouse.move(centered.x + centered.width / 2 + (bx - ax) * 0.1, centered.y + centered.height / 2 + (by - ay) * 0.1)
  await page.mouse.up(); await page.keyboard.up('Alt')
  const imageAfter = (await image.boundingBox())!
  expect(imageAfter.x + imageAfter.width / 2).toBeCloseTo(imageBefore.x + imageBefore.width / 2, 0)
  expect(imageAfter.y + imageAfter.height / 2).toBeCloseTo(imageBefore.y + imageBefore.height / 2, 0)
  expect(Number(await width.inputValue())).toBeGreaterThan(oldWidth)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  // Modifier rotation stays on a predictable angular increment.
  const r = (await page.getByLabel('Rotate artwork', { exact: true }).boundingBox())!
  await page.keyboard.down('Shift')
  await page.mouse.move(r.x + r.width / 2, r.y + r.height / 2)
  await page.mouse.down(); await page.mouse.move(r.x + 40, r.y + 30, { steps: 4 }); await page.mouse.up()
  await page.keyboard.up('Shift')
  expect(Number(await rotation.inputValue()) % 15).toBe(0)
})
